params:
  sample_size: 1000
  model_ckpt:  "distilbert-base-uncased"
  num_labels: 2
  batch_size: 32
  epochs: 3
  lr: 2e-5
  weight_decay: 0.01
paths:
  in_folder: ${hydra:runtime.cwd}/data/raw
  out_folder: ${hydra:runtime.cwd}/data/processed
